[package]
name = "reader-map"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
triomphe = { workspace = true }
smallvec = { workspace = true, features = ["union"] }
rand = { workspace = true }
left-right = { workspace = true }
itertools = { workspace = true }

readyset-client = { path = "../readyset-client" }
readyset-util = { path = "../readyset-util" }
partial-map = { path = "../partial-map" }
thiserror = { workspace = true }
iter-enum = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
test-strategy = { workspace = true }

