[package]
name = "reader-map"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
triomphe = { workspace = true }
smallvec = { workspace = true, features = ["union"] }
rand = { version = "0.7", default-features = false, features = ["std", "alloc"] }
left-right = { workspace = true }
itertools = { workspace = true }

readyset-client = { path = "../readyset-client" }
partial-map = { path = "../partial-map" }
thiserror = { workspace = true }
iter-enum = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
