[package]
name = "readyset-sql-parsing"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
clap = { workspace = true }
nom-sql = { path = "../nom-sql" }
paste = { workspace = true }
pretty_assertions = { workspace = true }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }
serde = { workspace = true, features = ["rc", "derive"] }
sqlparser = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
readyset-util = { path = "../readyset-util" }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }
test-strategy = { workspace = true }
test-utils = { path = "../test-utils" }

[[bench]]
name = "parse_comparison"
harness = false

[lints]
workspace = true
