[package]
name = "readyset-adapter-types"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

description = "Types shared between the adapter and database-specific front-end crates"

[dependencies]

# avoid depending on any readyset crates!

[lints]
workspace = true
