[package]
name = "replication-offset"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
readyset-sql = { path = "../readyset-sql" }
readyset-errors = { path = "../readyset-errors" }
serde = { workspace = true, features = ["derive"] }
readyset-util = { path = "../readyset-util" }
bytes = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
