[package]
name = "readyset-client-metrics"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
metrics = { workspace = true }
serde = { workspace = true }

# local dependencies
readyset-client = { path = "../readyset-client" }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
