[package]
name = "readyset-client-metrics"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
metrics = { workspace = true }
serde = "1.0.130"
serde_json = "1.0.67"

#local dependencies
readyset-client = { path = "../readyset-client" }
readyset-errors = { path = "../readyset-errors" }
nom-sql = { path = "../nom-sql" }

[lib]
path = "src/lib.rs"

