[package]
name = "partial-map"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
merging-interval-tree = { path = "../merging-interval-tree" }
readyset-util = { path = "../readyset-util" }

[lints]
workspace = true
