[package]
name = "readyset-alloc-metrics"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"


[dependencies]
metrics = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["release_max_level_debug"] }

# Local dependencies
readyset-alloc = { path = "../readyset-alloc" }
readyset-util = { path = "../readyset-util" }

[lints]
workspace = true
