[package]
name = "readyset-mysql"
version = "0.4.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
fail = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
metrics = { workspace = true }
mysql-srv = { path = "../mysql-srv" }
mysql_async = { workspace = true }
mysql_common = { workspace = true, features = ["bigdecimal", "binlog"] }
pem = { workspace = true }
pin-project = { workspace = true }
streaming-iterator = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["release_max_level_debug"] }

database-utils = { path = "../database-utils" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-adapter-types = { path = "../readyset-adapter-types" }
readyset-client = { path = "../readyset-client" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-shallow = { path = "../readyset-shallow" }
readyset-util = { path = "../readyset-util" }

[dev-dependencies]
chrono = { workspace = true }
futures = { workspace = true }
paste = { workspace = true }
proptest = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
test-strategy = { workspace = true }
yore = { workspace = true }

proptest-stateful = { path = "../proptest-stateful" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-client-test-helpers = { path = "../readyset-client-test-helpers" }
readyset-server = { path = "../readyset-server" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter", features = [
    "test-util",
] }
readyset-tracing = { path = "../readyset-tracing" }
test-utils = { path = "../test-utils" }

[features]
vertical_tests = []
# Redact the display of strings marked sensitive from logs and error messages
redact_sensitive = ["readyset-util/redact_sensitive"]
failure_injection = [
    "fail/failpoints",
    "readyset-server/failure_injection",
    "readyset-util/failure_injection",
]

[lints]
workspace = true
