# This file contains common build steps that can be included in other pipeline contexts.

# Non-buildkite nodes to re-use:
common_values:
  retry: &retry_on_agent_kill
    automatic: &agent_kill_conditions
      - signal_reason: agent_stop  # spot instance killed by AWS
        limit: 3
      - exit_status: -1            # agent timed out
        signal_reason: none
        limit: 3
steps:

  - label: 'Depends on first'
    depends_on: first
    commands:
      - echo 'second'
