# This file contains common build steps that can be included in other pipeline contexts.

# Non-buildkite nodes to re-use:
common_values:
  retry: &retry_on_agent_kill
    automatic: &agent_kill_conditions
      - signal_reason: agent_stop  # spot instance killed by AWS
        limit: 3
      - exit_status: -1            # agent timed out
        signal_reason: none
        limit: 3
steps:

  - label: ':rust: Run tests'
    key: rust-tests
    commands:
      - '[ -d public ] && cd public'
      - '.buildkite/run-tests.sh'
    timeout_in_minutes: 60
    depends_on:
    - build-image
    plugins:
      - docker-compose#v3.7.0:
          run: app
          env:
          - SCCACHE_BUCKET=readysettech-build-sccache-us-east-2
          - SCCACHE_REGION=us-east-2
          - CARGO_INCREMENTAL=0
          - RUST_BACKTRACE=full
          - MYSQL_HOST=mysql
          - MYSQL_PWD=noria
          - MYSQL_DB=noria
          volumes:
            - 'target:/workdir/target'
          config:
            - "${GIT_PUBLIC_ROOT}build/docker-compose.yml"
            - "${GIT_PUBLIC_ROOT}build/docker-compose.ci-test.yml"
          mount-buildkite-agent: true
          pull-retries: 3
      - ecr#v2.7.0:
          login: true
          retries: 3
    agents:
      queue: c6a-4xlarge
    retry: *retry_on_agent_kill
