# Non-buildkite nodes to re-use:
pipeline_build_image_values:
  retry: &retry_on_agent_kill
    automatic: &agent_kill_conditions
      - signal_reason: agent_stop  # spot instance killed by AWS
        limit: 3
      - exit_status: -1            # agent timed out
        signal_reason: none
        limit: 3

env:
  ECR_PLUGIN_VERSION: "v2.10.0"
  BUILDKIT_PROGRESS: "plain"

steps:

  - label: ":docker: Create build image: {{ matrix.arch }}"
    key: create-build-arch-image
    command: |
      [ -d public ] && cd public
      MULTIARCH=1 .buildkite/build-image.sh build/Dockerfile readyset-build .
    plugins:
      ecr#${ECR_PLUGIN_VERSION}:
        login: true
        retries: 3
    agents:
      queue: "{{ matrix.queue }}"
    retry: *retry_on_agent_kill
    matrix:
      setup:
        queue:
          - "c6a-4xlarge"
          - "c7g-4xlarge"
        arch:
          - "x86"
          - "arm"
      adjustments:
        - with:
            queue: "c6a-4xlarge"
            arch: "arm"
          skip: true
        - with:
            queue: "c7g-4xlarge"
            arch: "x86"
          skip: true

  - label: ':docker: Push build image manifest'
    key: push-build-image-manifest
    depends_on: create-build-arch-image
    command: |
      [ -d public ] && cd public
      .buildkite/push_docker_image_manifest.sh readyset-build
    plugins:
      ecr#${ECR_PLUGIN_VERSION}:
        login: true
        retries: 3
    retry: *retry_on_agent_kill
    agents:
      queue: t3a-small
