# This file contains steps for running the public OSS pipeline.  It defines
# steps required by the public build specifically, then includes the pipeline
# file containing common build steps.

# Non-buildkite nodes to re-use:
common_values:
  retry: &retry_on_agent_kill
    automatic: &agent_kill_conditions
      - signal_reason: agent_stop  # spot instance killed by AWS
        limit: 3
      - exit_status: -1            # agent timed out
        signal_reason: none
        limit: 3

steps:
  - label: ':docker: Build build image'
    key: build-image
    commands:
      - '.buildkite/build-image.sh build/Dockerfile readyset-build .'
    plugins:
      ecr#v2.5.0:
        login: true
        retries: 3
    retry: *retry_on_agent_kill

  - label: 'Run Postgres generated logictests %n'
    parallelism: 6
    key: logictest-generated-psql
    command:
    - 'echo +++ Running readyset-logictest'
    - ./run-psql-logictests.sh
    timeout_in_minutes: 1080
    depends_on:
    - build-image
    plugins:
      - docker-compose#v3.7.0:
          run: app
          env:
          - AUTHORITY=local
          - SCCACHE_BUCKET=readysettech-build-sccache-us-east-2
          - SCCACHE_REGION=us-east-2
          - CARGO_INCREMENTAL=0
          - RUST_BACKTRACE=full
          - LOG_LEVEL=error
          config:
            - public/build/docker-compose.yml
            - public/build/docker-compose.ci-test.yml
          pull-retries: 3
      - ecr#v2.5.0:
          login: true
          retries: 3
    agents:
      queue: r6a-4xlarge
    retry: *retry_on_agent_kill
