# This file contains steps for running the public OSS pipeline.  It defines
# steps required by the public build specifically, then includes the pipeline
# file containing common build steps.

# Non-buildkite nodes to re-use:
common_values:
  retry: &retry_on_agent_kill
    automatic: &agent_kill_conditions
      - signal_reason: agent_stop  # spot instance killed by AWS
        limit: 3
      - exit_status: -1            # agent timed out
        signal_reason: none
        limit: 3

env:
  ECR_PLUGIN_VERSION: "v2.10.0"
  BUILDKIT_PROGRESS: "plain"

steps:
  # TODO: ronh: decide what kind of linting we want in the OSS pipeline
  # - label: ':git: Lint commits'
  #   key: lint-commits
  #   branches: '!refs/heads/main'
  #   commands:
  #     - ./scripts/commit_lint.sh
  #   agents:
  #     queue: t3a-small

  - label: ":pipeline: Upload build image pipeline"
    key: build-image
    command: buildkite-agent pipeline upload public/.buildkite/pipeline.build-image.yml
    agents:
      queue: t3a-small
    retry: *retry_on_agent_kill

  - label: ':pipeline: Upload public-common pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/pipeline.public-common.yml
    depends_on: build-image
    agents:
      queue: t3a-small
