[package]
name = "test-utils"
version = "0.0.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
test-utils-proc-macros = { path = "./proc-macros" }
serial_test = { workspace = true }
pretty_assertions = { workspace = true }

# Avoid adding dependencies as this is included in tests.

[lints]
workspace = true
