[package]
name = "readyset-psql"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bit-vec = { workspace = true, features = ["serde"] }
cidr = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
eui48 = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
metrics = { workspace = true }
native-tls = { workspace = true }
postgres-native-tls = { workspace = true }
postgres-types = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true, features = [
    "with-chrono-0_4",
    "with-eui48-1",
    "with-uuid-0_8",
    "with-serde_json-1",
    "with-bit-vec-0_6",
] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
tracing-futures = { workspace = true }
uuid = { workspace = true }

database-utils = { path = "../database-utils" }
psql-srv = { path = "../psql-srv" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-adapter-types = { path = "../readyset-adapter-types" }
readyset-client = { path = "../readyset-client" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-data = { path = "../readyset-data" }
readyset-decimal = { path = "../readyset-decimal" }
readyset-errors = { path = "../readyset-errors" }
readyset-shallow = { path = "../readyset-shallow" }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-util = { path = "../readyset-util" }

[dev-dependencies]
chrono = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
test-strategy = { workspace = true }

readyset-client-test-helpers = { path = "../readyset-client-test-helpers" }
readyset-server = { path = "../readyset-server/" }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
readyset-tracing = { path = "../readyset-tracing" }
test-utils = { path = "../test-utils" }

[[bench]]
name = "proxy"
harness = false

[features]
# Redact the display of strings marked sensitive from logs and error messages
redact_sensitive = ["readyset-util/redact_sensitive"]
failure_injection = [
    "fail/failpoints",
    "readyset-server/failure_injection",
    "readyset-util/failure_injection",
]

[lints]
workspace = true
