[package]
name = "readyset-sql"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bit-vec = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
derive_more = { workspace = true }
eui48 = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
proptest = { workspace = true }
serde = { workspace = true }
sqlparser = { workspace = true }
strum = { workspace = true }
test-strategy = { workspace = true }
thiserror = { workspace = true }
triomphe = { workspace = true }

concrete-iter = { path = "../concrete-iter" }
readyset-decimal = { path = "../readyset-decimal" }
readyset-util = { path = "../readyset-util" }

[dev-dependencies]
bincode = { workspace = true }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
test-utils = { path = "../test-utils" }


[package.metadata.cargo-udeps.ignore]
# This is only used in doctests, which cargo-udeps can't detect.
normal = ["readyset-sql-parsing"]

[lints.clippy]
dbg_macro = "warn"
# During initial development, we are ok with todo!(); could remove them and just use workspace lints
todo = "allow"
