[package]
name = "readyset-dataflow"
version = "0.7.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

description = "Readyset dataflow crate"

[dependencies]
ahash = { workspace = true }
antithesis_sdk = { workspace = true }
async-bincode = { workspace = true }
bincode = { workspace = true }
bufstream = { workspace = true }
byteorder = { workspace = true }
clap = { workspace = true, features = ["derive"] }
criterion = { workspace = true, features = ["async_tokio"], optional = true }
derive_more = { workspace = true }
enum-kinds = { workspace = true }
exponential-backoff = { workspace = true }
fail = { workspace = true }
futures-util = { workspace = true }
html-escape = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
pin-project = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
socket2 = { workspace = true }
strum = { workspace = true }
test-strategy = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["net"] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
url = { workspace = true }
vec1 = { workspace = true }
vec_map = { workspace = true, features = ["eders"] }

# need features
petgraph = { workspace = true, features = ["serde-1"] }
serde = { workspace = true, features = ["rc"] }
timekeeper = { workspace = true }
smallvec = { workspace = true }

# local deps
common = { path = "../readyset-common", package = "readyset-common" }
dataflow-expression = { path = "../dataflow-expression" }
dataflow-state = { path = "../dataflow-state" }
failpoint-macros = { path = "../failpoint-macros" }
merging-interval-tree = { path = "../merging-interval-tree" }
reader-map = { path = "../reader-map" }
readyset-alloc = { path = "../readyset-alloc" }
readyset-client = { path = "../readyset-client" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }
readyset-util = { path = "../readyset-util" }
replication-offset = { path = "../replication-offset" }

[dev-dependencies]
test-utils = { path = "../test-utils" }

[features]
bench = ["criterion"]
failure_injection = ["fail/failpoints", "readyset-util/failure_injection"]
display_literals = []

[lints]
workspace = true
