[package]
name = "test-utils-proc-macros"
version = "0.0.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = [
    "full",
    "parsing",
    "printing",
    "proc-macro",
    "extra-traits",
    "clone-impls",
] }

[lints]
workspace = true
