[package]
name = "system-benchmarks"
version = "0.1.0"
edition = "2021"
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
publish = false

[dependencies]
anyhow = "1.0"
itertools = "0.10"
tokio = { workspace = true, features = ["full"] }
reqwest = { version = "0.11", features = [ "blocking" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-postgres = { workspace = true, features = ["with-chrono-0_4", "with-eui48-1", "with-uuid-0_8", "with-serde_json-1", "with-bit-vec-0_6"] }
database-utils = { path = "../database-utils" }
readyset-data = { path = "../readyset-data" }
clap = { workspace = true, features = ["derive"] }

[dev-dependencies]
benchmarks = { path = "../benchmarks" }
nom-sql = { path = "../nom-sql" }

readyset-client = { path = "../readyset-client" }
readyset-mysql = { path = "../readyset-mysql" }
readyset-psql = { path = "../readyset-psql" }
readyset = { path = "../readyset" }

core_affinity = "0.5"
criterion = { version = "0.3", features = ["async_tokio"] }
fork = "0.1"
futures = "0.3"
num_cpus = "1.13"
parking_lot = "0.12"
temp-dir = "0.1"
tikv-jemallocator = "0.5"

regex = "1.5"

bincode = "1.3"

nperf-core = { workspace = true }
structopt = "0.2"
libc = "0.2"

[[bin]]
name = "regressions"
test = false
bench = false

[[bench]]
name = "workload"
harness = false
