[profile.default]
# This one test is absurdly long locally even compared to other tests marked slow, and not very
# valuable unless you're working on related code. In which case, run with --ignore-default-filter.
default-filter = 'not test(test_large_packet_write)'

[profile.ci]
default-filter = 'all()'
fail-fast = false
retries = 1
failure-output = "immediate-final"

[test-groups]
serial = { max-threads = 1 }
serial-postgres = { max-threads = 1 }
serial-mysql = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(/:serial:/) and not (test(/:postgres\d*_upstream:/) or test(/:mysql\d*_upstream:/))'
test-group = 'serial'

[[profile.default.overrides]]
filter = 'test(/:serial:/) and test(/:postgres\d*_upstream:/)'
test-group = 'serial-postgres'

[[profile.default.overrides]]
filter = 'test(/:serial:/) and test(/:mysql\d*_upstream:/)'
test-group = 'serial-mysql'

[[profile.default.overrides]]
filter = 'test(/:proptest:/)'
retries = 0
