[profile.default]
# Some default exclusions for devs who just want to run `cargo nextest run`. If you want to run all
# tests including these, either use the `ci` profile (--profile ci), or remove the default filter
# (`--ignore-default-filter`).
#
# - `test_large_packet_write` is absurdly long locally even compared to other tests marked slow, and
#   not very valuable unless you're working on related code.
# - `clustertests` are slow, unreliable, and require building their own copy of readyset.
default-filter = 'not test(test_large_packet_write) and not package(readyset-clustertest)'

[profile.ci]
default-filter = 'not package(readyset-clustertest)'
fail-fast = false
retries = 1
failure-output = "immediate-final"
slow-timeout = { period = "60s", terminate-after = 5, grace-period = "20s" }

[profile.ci.junit]
path = "junit.xml"
store-success-output = true
store-failure-output = true

[test-groups]
serial = { max-threads = 1 }
serial-postgres = { max-threads = 1 }
serial-mysql = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(/:serial:/) and not (test(/:postgres\d*_upstream:/) or test(/:mysql\d*_upstream:/))'
test-group = 'serial'

[[profile.default.overrides]]
filter = 'test(/:serial:/) and test(/:postgres\d*_upstream:/)'
test-group = 'serial-postgres'

[[profile.default.overrides]]
filter = 'test(/:serial:/) and test(/:mysql\d*_upstream:/)'
test-group = 'serial-mysql'

[[profile.default.overrides]]
filter = 'test(/:proptest:/)'
retries = 0
