---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ required "You must pass a namespace" (.Release.Namespace | quote) }}
  name: readyset-adapter
  labels: {{ include "readyset.labels" . | nindent 4 }}
  {{- if .Values.readyset.adapter.service.annotations }}
  annotations:
    {{- include .Values.readyset.adapter.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.readyset.adapter.service.type | default "LoadBalancer" }}
  selector:
    app.kubernetes.io/name: "readyset"
    app.kubernetes.io/component: "adapter"
  ports:
    - name: {{ ( include "readyset.adapter.type" . ) }}
      port: {{ ( include "readyset.adapter.port" . ) }}
      targetPort: {{ ( include "readyset.adapter.port" . ) }}
      protocol: TCP
    - name: monitoring
      port: {{ ( include "readyset.adapter.httpPort" . ) }}
      targetPort: {{ ( include "readyset.adapter.httpPort" . ) }}
      protocol: TCP
