[package]
name = "readyset"
version = "1.2.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"


[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive","env"] }
futures-util = { workspace = true }
fail = { workspace = true }
failpoint-macros = { path = "../failpoint-macros" }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-native-tls = { workspace = true }
tokio-stream = { workspace = true, features = ["net"] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
tracing-subscriber = { workspace = true }
tracing-futures = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
chrono = { workspace = true }
crossbeam-skiplist = { workspace = true }

# Local dependencies
health-reporter = { path = "../health-reporter" }
readyset-util = { path = "../readyset-util" }
nom-sql = { path = "../nom-sql" }
mysql-srv = { path = "../mysql-srv" }
psql-srv = { path = "../psql-srv" }
database-utils = { path = "../database-utils" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-alloc = { path = "../readyset-alloc" }
readyset-alloc-metrics = { path = "../readyset-alloc-metrics" }
readyset-client = { path = "../readyset-client/" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-common = { path = "../readyset-common" }
readyset-data = { path = "../readyset-data" }
readyset-dataflow = { path = "../readyset-dataflow" }
readyset-errors = { path = "../readyset-errors" }
readyset-mysql = { path = "../readyset-mysql" }
readyset-psql = { path = "../readyset-psql" }
readyset-server = { path = "../readyset-server/" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-version = { path = "../readyset-version" }
replicators = { path = "../replicators" }
serde_json = { workspace = true }


[dev-dependencies]
serial_test = { workspace = true }
temp-dir = { workspace = true }

[features]
failure_injection = ["fail/failpoints", "readyset-client/failure_injection", "readyset-server/failure_injection"]

[package.metadata.deb]
maintainer = "ReadySet Technology <info@readyset.io>"
copyright = "2023, ReadySet Technology, Inc."
license-file = ["../LICENSE", "1"]
extended-description = """\
A real-time SQL caching engine for Postgres and MySQL."""
depends = "$auto"
section = "Databases"
priority = "optional"
assets = [
    ["target/release/readyset", "usr/bin/", "755"],
    ["debian/readyset.conf", "/etc/readyset/readyset.conf", "644"],
    ["debian/systemd/readyset.service", "/lib/systemd/system/readyset.service", "644"],
]
maintainer-scripts = "debian/scripts"
conf-files = ["/etc/readyset/readyset.conf"]
