[package]
name = "readyset"
version = "1.3.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"
license = "BSL 1.1"
description = """\
A real-time SQL caching engine for Postgres and MySQL."""


[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { workspace = true, features = ["derive","env"] }
futures-util = "0.3.0"
fail = "0.5.0"
failpoint-macros = { path = "../failpoint-macros" }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-stream = { version = "0.1.5", features = ["net"] }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-subscriber = "0.3.9"
tracing-futures = "0.2.5"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
crossbeam-skiplist = "0.1.1"

# Local dependencies
health-reporter = { path = "../health-reporter" }
readyset-util = { path = "../readyset-util" }
nom-sql = { path = "../nom-sql" }
mysql-srv = { path = "../mysql-srv" }
psql-srv = { path = "../psql-srv" }
database-utils = { path = "../database-utils" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-alloc = { path = "../readyset-alloc" }
readyset-alloc-metrics = { path = "../readyset-alloc-metrics" }
readyset-client = { path = "../readyset-client/" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-common = { path = "../readyset-common" }
readyset-data = { path = "../readyset-data" }
readyset-dataflow = { path = "../readyset-dataflow" }
readyset-errors = { path = "../readyset-errors" }
readyset-mysql = { path = "../readyset-mysql" }
readyset-psql = { path = "../readyset-psql" }
readyset-server = { path = "../readyset-server/" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-version = { path = "../readyset-version" }
replicators = { path = "../replicators" }
serde_json = "1.0.89"
url = "2.2.2"


[dev-dependencies]
serial_test = "0.5"
temp-dir = "0.1"

[features]
failure_injection = ["fail/failpoints", "readyset-client/failure_injection", "readyset-server/failure_injection"]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/readyset", dest = "/usr/bin/readyset", mode = "755" },
    { source = "pkg/common/readyset.conf", dest = "/etc/readyset/readyset.conf", mode = "600", config = true },
    { source = "pkg/common/readyset.service", dest = "/lib/systemd/system/readyset.service", mode = "644" },
]
# These get set using cargo-generate-rpm --metadata-overwrite=<SCRIPTLETS.TOML> at package build time.
#post_install_script = ...
#pre_uninstall_script = ...
#post_uninstall_script = ...


[package.metadata.deb]
maintainer = "Readyset Technology <info@readyset.io>"
copyright = "2024, Readyset Technology, Inc."
license-file = ["../LICENSE", "1"]
depends = "$auto"
section = "Databases"
priority = "optional"
assets = [
    ["target/release/readyset", "usr/bin/", "755"],
    ["pkg/common/readyset.conf", "/etc/readyset/readyset.conf", "600"],
    ["pkg/common/readyset.service", "/lib/systemd/system/readyset.service", "644"],
]
maintainer-scripts = "pkg/debian"
conf-files = ["/etc/readyset/readyset.conf"]
