[package]
name = "replicators"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
atoi = { workspace = true }
bit-vec = { workspace = true, features = ["serde"] }
bytes = { workspace = true }
chrono = { workspace = true }
deadpool-postgres = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
mysql_async = { workspace = true }
mysql_common = { workspace = true, features = ["binlog"] }
native-tls = { workspace = true }
nom_locate = { workspace = true }
paste = { workspace = true }
postgres-native-tls = { workspace = true }
postgres-protocol = { workspace = true }
postgres-types = { workspace = true, features = [
    "with-chrono-0_4",
    "with-serde_json-1",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true, features = [
    "with-chrono-0_4",
    "with-serde_json-1",
] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
tracing-futures = { workspace = true }
database-utils = { path = "../database-utils" }
failpoint-macros = { path = "../failpoint-macros" }
mysql-srv = { path = "../mysql-srv" }
mysql-time = { path = "../mysql-time" }
nom-sql = { path = "../nom-sql" }
readyset-client = { path = "../readyset-client" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-util = { path = "../readyset-util" }
readyset-decimal = { path = "../readyset-decimal" }
replication-offset = { path = "../replication-offset" }

[dev-dependencies]
bincode = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
proptest-stateful = { path = "../proptest-stateful" }
rand = { workspace = true }
readyset-client-test-helpers = { path = "../readyset-client-test-helpers", features = [
    "mysql",
    "postgres",
] }
readyset-server = { path = "../readyset-server" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter", features = [
    "test-util",
] }
reqwest = { workspace = true }
test-strategy = { workspace = true }
test-utils = { path = "../test-utils" }

[features]
vertical_tests = []
failure_injection = ["fail/failpoints", "readyset-util/failure_injection"]

[lints]
workspace = true
