[package]
name = "readyset-tracing"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
opentelemetry-semantic-conventions = { workspace = true, features = [
    "semconv_experimental",
] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
pyroscope = { workspace = true }
pyroscope_pprofrs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[dev-dependencies]
tracing-attributes = { workspace = true }

[lints]
workspace = true
