[package]
name = "data-generator"
publish = false
version = "0.1.0"
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bit-vec = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
eui48 = { workspace = true }
growable-bloom-filter = { workspace = true }
rand = { workspace = true }
rand_regex = { workspace = true }
uuid = { workspace = true }
rand_distr = { workspace = true }

readyset-sql = { path = "../readyset-sql" }
readyset-data = { path = "../readyset-data" }
readyset-decimal = { path = "../readyset-decimal" }

[dev-dependencies]
test-strategy = { workspace = true }
proptest = { workspace = true }
mysql_async = { workspace = true }
tokio = { workspace = true, features = ["full"] }
test-utils = { path = "../test-utils" }

[lints]
workspace = true
